### ISSUE TITLE
Directories are mapped against actual windows folders instead of volumes

### ISSUE THREAD

**Issue by snipercup** [Atinoda/text-generation-webui-docker#12]
Amazing work! It was very easy to use! I followed all the instructions and successfully ran a container. I thought the folders inside the image would be mapped to volumes inside docker desktop, but they are linked to windows folders:

![image](https://github.com/Atinoda/text-generation-webui-docker/assets/50166150/59c8f0b1-762e-4cad-8dd5-b687d10c5987)

Why is it configured this way and not using the volumes that docker themselves recommend? Docker volumes increase portability and persist after updating the container just as well.

I am using Windows 11 home edition + WSL running a NVidea GTX 3060 and cuda GPU acceleration seems to work just fine.

**Comment by Atinoda** [comment]
Hi @snipercup - I'm glad that the image works well for you and wasn't difficult to set up, and thank you for reporting your hardware and OS to be working under W11 with WSL! You raise an interesting point about not using volumes, and I did consider it when I was first writing the Dockerfile. My thinking is along these lines:
- Text generation web ui is being developed quickly, so the configs may break between versions *(e.g., the removal of the `softprompts` folder)*
- If configs can break between updates then they shouldn't persist by default -> don't use volumes
- However, it is important to be able to persist configs, so it should be a manual but easy option -> users must define mapped folders, but examples are included in the `docker-compose.yml`

Ultimately, it's down to a matter of taste. I run almost all of my services using docker these days, and I very much prefer to use mapped folders to volumes - they can be explored and edited from the host computer, they're easy to copy and migrate from one place to another, they're easy to backup and rollback using file explorer, folders can be shared across instances (looking at you, absolutely massive `models` folder). In my personal deployments of this image I only map across `models` and `training`, sometimes an extension or two as well.

All that being said - I don't run docker in Windows much at all, so I don't know if this tracks across to the experience there. How do you find the workflow with mapped folders? Is it awkward on Windows? I will consider adding some thoughts to the `README.md` as usage guidance.

**Comment by snipercup** [comment]
Ooh I see. So you did consider both options. That's good. I only downloaded docker today so I don't know a whole lot about it. Docker desktop clearly shows where the folders are mapped to, so it's not awkward. I wanted volumes mostly to contain the data safely and delete it when I don't need it, but I can do that with folders as well.
