### ISSUE TITLE
 Unable to Save Characters in Chat Mode

### ISSUE THREAD

**Issue by czjyyds** [Atinoda/text-generation-webui-docker#14]
**Steps to Reproduce:**

1. Enable Chat Mode.
2. Navigate to Chat Settings and select the Characters tab.
3. Enter a new character and attempt to save it.
4. When prompted, enter a file name.

**Expected Behavior:**
The character's YAML file should be successfully saved in the character directory. The character should be available for selection even after reloading.

**Actual Behavior:**
The character's YAML file is not created, and the character is not available for selection after reloading.

**Comment by Atinoda** [comment]
To quote a famous developer, *"It works on my machine"*

However, I did recently add the `character` folder to config defaults, with initialise and map in the `docker-entrypoint.sh` script and the example `docker-compose.yml`, so there was a small change yesterday. Was this feature working for you before? Have you made any changes to your config recently? Does the docker console log throw any errors?

If you have developed special characters in the past, please be careful that you do not delete them! They may be inside the docker container instance. The files can be easily extracted but you should not remove / `down -v` / destroy the container while you're testing anything.

**Comment by Atinoda** [comment]
Closing this issue, as I can't replicate the problem. Please re-open if you have further comments.
