### ISSUE TITLE
Error :  arrow::fs::FinalizeS3 was not called even though S3 was initialized

### ISSUE THREAD

**Issue by ksingh-scogo** [Atinoda/text-generation-webui-docker#15]
Getting this error while `docker compose up`
<img width="1725" alt="image" src="https://github.com/Atinoda/text-generation-webui-docker/assets/76433381/d2eddb3e-6029-4c73-925f-bdd02f75e175">

This is using default tag of the container image

is this known  ?

**Comment by ksingh-scogo** [comment]
Next trying `default-nightly` container image tag

**Comment by Atinoda** [comment]
Hi there, thanks for trying out the repo!

The error is saying that your CUDA version on the docker host is too old to run the container. I also notice a reference to `s3fs` - are you trying to run this on an AWS instance?

Can you please provide more info on your system environment and deployment? I'll see if I can help.

**Comment by Atinoda** [comment]
I'm assuming that this is the same issue as #16, which should have been resolved by 00340c05045dda1e0bc67e7deb7f6ef22859a865 - so I will close it for now. Please feel free to re-open if you believe that something else is afoot!
