### ISSUE TITLE
older images?

### ISSUE THREAD

**Issue by syaoran68** [Atinoda/text-generation-webui-docker#18]
Hello!
I just stumbled upon this and think this is a great addition to the quick deployment capabilities for text-generation-ui.

Looking through the code updates it looks we're about 2 weeks behind, but also looking at the image tags, we track a default stable build and a nightly build.

I'm wondering why there aren't any older builds? normally on docker-hub you can revert back if necessary, but i don't see any of the older images. will this be an option in the future?

Thank you!

**Comment by Atinoda** [comment]
Hi, I'm glad that you like the repo and thank you for your kind words!

When I first put this image together, `text-generation-webui` was not doing point releases - but I see that it is now. I agree with you on the ability to roll back, and I will being publishing point release docker images corresponding to oobabooga's project milestones. Thank you for prompting me to check that out again :)

**Comment by Atinoda** [comment]
Version-tagged images are now implemented (including a ret-con of the old versions)
