### ISSUE TITLE
Where i have to upload the training-dataset?

### ISSUE THREAD

**Issue by DietmarGrabowski** [Atinoda/text-generation-webui-docker#19]
i, i am running 'Oobabooga LLM WebUI ', everything is fine, but now i am try to upload  a training-dataset to  /app/training/datasets.
But the gui does not found anything, also the /app/models/ is empty but a model is working.
Where i have to upload the training-dataset?
Thx

**Comment by Atinoda** [comment]
Glad that you got it running! I'm sorry, but that's not really enough information for me to help you. The container should is able to read and write any files that are placed into those folders, if you have mapped them in the `docker-compose.yml`.

What OS are you running? What hardware? What docker stack? Have you mapped those folders into the container? I cannot offer you useful advice without more details.

**Comment by DietmarGrabowski** [comment]
Hi, thank you, i am using https://cloud.vast.ai/
they are using your docker-file as template, i think they don't changed anything.
https://cloud.vast.ai/template
System: Linux 36b6b4e003b0 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Atinoda** [comment]
That's cool to see it deployed in the cloud! Unfortunately, *vast.ai* don't give information about their template deployment details to see how storage is configured. I notice they have a chat pop-up - I think that you should talk to their technical support to find out this information. You will need to access the instance's storage to upload a training dataset. Training works correctly in the image, and I have used it to create LoRAs from custom datasets in the past.

**Comment by DietmarGrabowski** [comment]
Hi, thank you, i found the model-path, it is at /src, don't ask me why :-)

**Comment by Atinoda** [comment]
That's awesome, thank you for sharing that you got it fixed. You're right that they made an unusual choice there - I would have expected the root of the app to be at `/app`, haha!
