### ISSUE TITLE
Allow persistent extensions

### ISSUE THREAD

**Issue by Wrexthor** [Atinoda/text-generation-webui-docker#3]
Would be very helpful with ability to use extensions.

**Comment by Atinoda** [comment]
Thanks - this a timely issue! By coincidence I was thinking about extensions this morning, specifically how to install additional third party ones and how to modify the bundled ones. I will do something about it this weekend, need to think through a few different ways of handling that.

Would you mind describing your use case or thoughts in some more detail? I will bear it in mind when I'm thinking of solutions, and it would help to have another perspective as well to make sure the solution is generalised.
