### ISSUE TITLE
Trying to load EXL2 with default-nightly image fails

### ISSUE THREAD

**Issue by accountForIssues** [Atinoda/text-generation-webui-docker#31]
Tried yesterday and today. Loading an EXL2 model fails with the below error. Tried with EXL2 and EXL2_HF loaders.

The models load successfully and work fine with the `default` image.

![image](https://github.com/Atinoda/text-generation-webui-docker/assets/52367365/c7212000-2a5e-4b07-810c-84f7fb913eeb)

**Comment by Atinoda** [comment]
Thank you for spotting and reporting this issue! It should be fixed now, in the latest snapshot and nightlies going forwards.
