### ISSUE TITLE
Error when loading some GGUF files with llama.cpp

### ISSUE THREAD

**Issue by silverwind63** [Atinoda/text-generation-webui-docker#32]
My spec:RTX 3060ti,R5 5600X,16GB ram
I want to load deepseek models I have tried deepseek 6.7B and 33B,and neither of these models work. I have run several 7B,14B,34B models and it work without any problems. When I want to load deepseek model, the webui just crashed immediately.

Here is the error output from terminal:
```
text-generation-webui  | llama_model_loader: - type  f32:   65 tensors
text-generation-webui  | llama_model_loader: - type q6_K:  226 tensors
text-generation-webui  | ERROR: byte not found in vocab: '
text-generation-webui  | '
text-generation-webui  | /scripts/docker-entrypoint.sh: line 69:    98 Segmentation fault      (core dumped) "${LAUNCHER[@]}"
text-generation-webui exited with code 139
chj@archlinux /m/m/text-generation-webui-docker (master)> 
```

**Comment by FKouhai** [comment]
this might sound quite obnoxious, but it seems to work on my computer, im running:

-  TheBloke/deepseek-coder-6.7B-instruct-GGUF
- deepseek-coder-6.7b-instruct.Q4_K_M.gguf

My HW specs:

ryzen 7 2700x
32GB RAM
nvidia 3060 12GB


You probably want to be using a newer version of the docker image, im currently running atinoda/text-generation-webui:default-snapshot-2023-12-17
