### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by seyyaw** [Atinoda/text-generation-webui-docker#34]
I just try to start it as `docker compose up` and faced the following error.

`FileNotFoundError: [Errno 2] No such file or directory: 'presets/simple-1.yaml'`

Any idea how to fix this?

Thanks

**Comment by Atinoda** [comment]
is [this part](https://github.com/Atinoda/text-generation-webui-docker#volumes) of the `README.md` relevant? Specifically, _"If you are getting an error about missing files, try clearing these folders and letting the service re-populate them."_

Make sure to back up any custom presets beforehand!

**Comment by Atinoda** [comment]
I cannot replicate this issue with a clean install - please try recreating a clean `config` folder on your machine.
