### ISSUE TITLE
no launch args --subpath

### ISSUE THREAD

**Issue by SnowWindDancing** [Atinoda/text-generation-webui-docker#35]
It seems that an update is needed.
https://github.com/oobabooga/text-generation-webui/pull/1538/files

**Comment by Atinoda** [comment]
Thank you for linking this change - it saves me a lot of time digging through code! I didn't get a chance to refactor this project over Christmas but I intend to do some serious development work to it next week.

**Comment by Atinoda** [comment]
The updates should have fixed this issue. Please re-open if not.
