### ISSUE TITLE
exec /scripts/docker-entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by thejacer** [Atinoda/text-generation-webui-docker#36]
No build errors, however I noticed the container wasn't actually launching. Ran with logs and this is all it produced.

ubuntu:~/text-generation-webui-docker$ sudo docker-compose logs -f
Attaching to text-generation-webui
text-generation-webui           | exec /scripts/docker-entrypoint.sh: exec format error
text-generation-webui exited with code 1

**Comment by Atinoda** [comment]
Unfortunately I did not get a chance to refactor this project over Christmas and it needs some work to bring it up to date. I intend to have everything working again next week. In the meantime, try pulling the latest stable image from dockerhub or building against an older checkout of the source.

**Comment by Atinoda** [comment]
The updates should have fixed this issue. Please re-open if not.
