### ISSUE TITLE
Update dependencies for getting LLAMA 3.1 to work

### ISSUE THREAD

**Issue by reuschling** [Atinoda/text-generation-webui-docker#54]
Now LLAMA 3.1 is out, but sadly it is not loadable with current text-generation-webui-docker. I tried to update transformers lib which makes the model loadable, but I further get an error when trying to use the model:
```
Traceback (most recent call last):
  File "/app/modules/callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/app/modules/text_generation.py", line 393, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1975, in generate
    self._get_logits_warper(generation_config, device=input_ids.device)
TypeError: get_logits_warper_patch() got an unexpected keyword argument 'device'
```

When I updated torch, I come into further issues and found myself in the dependency hell...

Here is some discussion about needed library versions, as a hint:
https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/discussions/15
https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/discussions/35

**Comment by Atinoda** [comment]
Hi @reuschling, thank you for reporting the issue with Llama 3.1 and providing the links to the discussions. I ran into some issues with my network and server upgrades which pulled me away from this project... Thankfully, these are now resolved and I'll be spending some time to bring this container up to date! I'll make sure to check compatibility with Llama 3.1 during the process.

**Comment by Atinoda** [comment]
I briefly tested [hugging-quants/Meta-Llama-3.1-8B-BNB-NF4](https://huggingface.co/hugging-quants/Meta-Llama-3.1-8B-BNB-NF4/tree/main) and it works. Please let me know if you encounter any issues with Llama 3.1 models.

**Comment by reuschling** [comment]
Works in my setting also, thanks a lot!
