### ISSUE TITLE
Support webui 1.13.0

### ISSUE THREAD

**Issue by fzyzcjy** [Atinoda/text-generation-webui-docker#55]
Hi thanks for the docker image! Looks like webui 1.13.0 is released with llama.cpp supporting llama 3.1, thus it would be great to have it.

**Comment by Atinoda** [comment]
Hi @fzyzcjy, thank you for the heads up! The build for v1.13 is available now.

If a new feature is released in the future and I have not yet published updated images, the nightly builds should have it included. Llama-3.1was briefly tested in v1.12 and also appears to be working - details are in #54.

**Comment by fzyzcjy** [comment]
You are welcome and thank you!
