### ISSUE TITLE
Upgrade torch version with the README documentation version

### ISSUE THREAD

**Issue by nicokim** [Atinoda/text-generation-webui-docker#58]
I'm having this error while loading an exllamav2 quantization:

ImportError: /venv/lib/python3.10/site-packages/exllamav2_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda14ExchangeDeviceEa

I think the problem is that in the dockerfile has a different pytorch version installed, these are the requirements in the oobabooga docs:

| System | GPU | Command |
|--------|---------|---------|
| Linux/WSL | NVIDIA | `pip3 install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu121` |
| Linux/WSL | CPU only | `pip3 install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cpu` |
| Linux | AMD | `pip3 install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/rocm6.1` |
| MacOS + MPS | Any | `pip3 install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1` |
| Windows | NVIDIA | `pip3 install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu121` |
| Windows | CPU only | `pip3 install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1` |

**Comment by Atinoda** [comment]
Hi @nicokim, thanks for letting me know about the version mismatch! What image tag are you running?

**Comment by nicokim** [comment]
Yeah the tags that I have problem are: default-nvidia-nightly and default-nvidia tags

**Comment by Atinoda** [comment]
Can you please confirm if you have this issue on both `default-nvidia-nightly` and `default-nvidia`? I would expect problems with nightly, but not default.

**Comment by nicokim** [comment]
![image](https://github.com/user-attachments/assets/89e43132-f3b0-476f-907f-484a4cf3d9dd)
Sure, here as screenshot of the error that I have while loading a finetuning that I had. The problem is that in this new finetuning I used the newest finetuning version and it doesn't work in default-nvidia.

**Comment by Atinoda** [comment]
I believe the latest update addresses this issue - please re-open if not working.
