### ISSUE TITLE
connection refused issue

### ISSUE THREAD

**Issue by sdlzen** [Atinoda/text-generation-webui-docker#7]
Can not seem to connect to webui through any means due to err connection refused, checked all firewall settings etc, appears to me that this may be the root of the issue:

https://pythonspeed.com/articles/docker-connection-refused/
As a newbie to all this, not been able to fix yet.

**Comment by sdlzen** [comment]
this is no longer an issue, misconfiguration

**Comment by Atinoda** [comment]
Thanks for your message and opening the issue to share! Would you be willing to write up what the problem and fix were in this closed issue? Just in case somebody else lands here from a search.

**Comment by sdlzen** [comment]
Sure...

Running from docker desktop on windows, certainly for me the --listen argument is not set as default within the image, I see now they could be set in docker-compose.yml. This is my first time using docker!

Docker has reportedly fixed the issue mentioned in the article I shared above following a version update some time back.

As a fix, since I was running on cublas I changed the below running prompt from the readme.

from:
docker run --it --rm --gpus all -p 7860:7860 atinoda/text-generation-webui:default

to: 
docker run -it -e EXTRA_LAUNCH_ARGS="--listen" --rm --gpus all -p 7860:7860 atinoda/text-generation-webui:llama-cublas

If you run either direct from docker desktop, or in terminal without using -e EXTRA_LAUNCH_ARGS="--listen", or without changing this in the docker-compose.yml file then you will face a connection refused error from the webapp, even though the docker terminal will show that the app is running fine.

Using -e to pass in the launch arguments in this way is just a personal preference to control directly from terminal.

You can set any of the launch arguments in this way, but the above is fine to run cublas with GPU support.

Now all working - just keeping in mind that anyone copying the above way to launch, you will have to import your model to docker each time as this runs without any persistence, using docker desktop you can do this by going to the running container, clicking on the files tab and drag dropping your model into the folder: app/models.

**Comment by Atinoda** [comment]
Thanks very much @sdlzen! I'm sure that other people will find what you've written useful :)

I'm going to put aside an evening to improve Windows support in the near future, and I'll definitely refer back to what you've shared here. Hopefully can make some updates to the project so that it is a smoother process getting it working on Windows.

**Comment by sdlzen** [comment]
The other thing I'd add - in case someone tries to hack this together like I did without knowledge of docker etc- is if I try to run it using atinoda/text-generation-webui:default after having installed as atinoda/text-generation-webui:llama-cublas, it doesn't see that there is llama-cublas, instead it will just start a new pull request also which is not necessary.

**Comment by Atinoda** [comment]
Thanks for the additional info about the variants behaviour too. I've added your `EXTRA_LAUNCH_ARGS` fix to the `README.md` right now, and I'll also check into more detail when I do my *Windows day*! If you have any other suggestions, bugs/fixes, or ideas about Windows, please open issues for them or drop a message here and I'll look at them too. Equally, you are welcome (but not obligated!) to submit a PR if you'd like to try contributing some code or docs directly.
