### ISSUE TITLE
Training in 4-bit

### ISSUE THREAD

**Issue by Jeduh** [Atinoda/text-generation-webui-docker#8]
Hi, How do I train a LORA with a GPTQ 4-bit model as its base? I tried with and without the new monkeypatch and with all the different model loaders. I got the furthest by trying to use AutoGPTQ without monkeypatch, and got this response:

285, in _create_new_module raise ValueError( ValueError: Target module QuantLinear() is not supported. Currently, only torch.nn.Linear and Conv1D are supported.

just like this [issue ](https://github.com/oobabooga/text-generation-webui/issues/2714)

**Comment by Atinoda** [comment]
Glad to hear that you're diving into LoRA training! The monkey-patch technique is quite old but I've just checked upstream and I see that they're doing some updates. I will keep an eye on how things develop before I start making structural changes to this repo. What GPU and OS are you running?

For now, I suggest that you use the `default` variant, use the Transformers loader (that's just 'plain' huggingface models - not GGML or GPTQ), and check the `load-in-4-bit` option. I am able to train [ehartford/WizardLM-7B-Uncensored](https://huggingface.co/ehartford/WizardLM-7B-Uncensored) 4-bit LoRAs on an RTX3090 using these options. I think this is what Ph0rk0z is referring to in the link that you sent with *"You can train with qlora (full size files)..."*

It seems that it also possible to train LoRAs on modern GPTQ models, but it is not something I am currently doing.

**Comment by Jeduh** [comment]
Thank you :)

using a 3090 and ubuntu.

Im trying to train a it with a modified monkeypatch based on [this](https://github.com/vihangd/alpaca-qlora/blob/main/experiments/llama_rope_scaled_monkey_patch.py) so that i can train with scaled position embedding from [this](https://kaiokendev.github.io/til#extending-context-to-8k) post but i cant get the alpaca lora 4bit modified monkey patch to even load. Sometimes it says cannot find monkeypatch. 

Ill give it a shot but i have no idea how to add the code i need to that though. Any ideas?

**Comment by Atinoda** [comment]
Your system is well aligned with the project! That's basically what I run as the main LLM rig too. I think that the Transformers loader method I described previously is using qlora technique (but I haven't taken the time to actually dig into the code - so i cannot say for sure). If the built-in trainer is sufficient then you do not need to run any code. If you're trying to modify textgen's training behaviour then you're in for a fair bit of development work!

Are you trying to achieve a longer context length?

**Comment by Jeduh** [comment]
Yuppp, you interested?

**Comment by Atinoda** [comment]
Extended context is on my hit-list as well. Have you had any joy so far?

I still need to have a read through: https://github.com/epfml/landmark-attention which seemed promising.

**Comment by Jeduh** [comment]
It was very promising and literally 2 days old. Is there any way i can contact you?

**Comment by Jeduh** [comment]
Id go as far as saying, drop what youre working on to check this out, they cracked it

**Comment by Atinoda** [comment]
Which guys cracked it - the ones you linked earlier? If there's off-the-shelf code to be integrated into textgen or deployable by Docker then that's exactly what I'll do!

I'm currently working on a large-ish project that integrates LLMs, and extended context is due for investigation a little bit later on. If I get to that point and there's nothing deployable then I'll have a go at coding a solution out of papers.

**Comment by Jeduh** [comment]
Oh bro, its literally 2 lines of code. Yeah that guy but inspired by the attention god

**Comment by Jeduh** [comment]
Also, me too :)

**Comment by Atinoda** [comment]
Thanks man, it's good to see other people's excitement and that you spotted that paper too! I'll need to sit down and read it properly soon, then go through their code and try running some implementations.

If you're using textgen as your platform, I do not think that you can run highly customised models and training regimes like that without, at the very least, a custom extension - but probably it will require a customised branch of the source code. That's not as bad as it sounds though, my production build uses a custom fork of textgen with some extra features that I need (and it runs using this repo's `docker-compose.yml.build`)

**Comment by Jeduh** [comment]
Its not a paper, just a description of a discovery, at least look at the graph, it compares it to older attempts. You need to see why im so hyped hahahhaha

**Comment by Jeduh** [comment]
> That's not as bad as it sounds though, my production build uses a custom fork of textgen with some extra features that I need (and it runs using this repo's `docker-compose.yml.build`

Sweet, lil easter egg :)

**Comment by Jeduh** [comment]
![ppl](https://github.com/Atinoda/text-generation-webui-docker/assets/98840691/551b6458-06e7-4a7f-b580-34d17e68ef26)

And

`        # These two lines:
        self.scale = 1 / 4
        t *= self.scale`

**Comment by Atinoda** [comment]
I've flicked through that link and it does indeed look promising - I'm definitely saving that for later. Unfortunately the two lines of code described there are pretty low-level from my understanding (i.e., it's "only two bricks to move" but those two bricks are at the bottom of the wall on the ground floor of a skyscraper!). Nevertheless, if someone hasn't moved those bricks around in one of the major inference libraries by the time I'm looking at extended context, I will attempt it.

**Comment by Jeduh** [comment]
Actually, it was pretty easy, I managed to port it to Alpaca lora 4 bit but would couldnt even get it to run anymore, with or without the updated monkeypatch.

Here a little summary. LLM's have been trained with tokens alone side their positional embeddings. For llama, this is 2048. Now what if we decoupled the positional embedding with the amount of tokens fed in. We could extrapolate and run with 2049 and beyond but we've tried it and the line in yellow shows its limitations. This is where the realisation that the models have been always trained on their max limit comes in, with going beyond 2048 llama is like "huh, wtf is this" so what next? lets work within the 2048 with scalling. If we make it so every other token is 1/2 a positional token eg 0.5,1,1.5... then we essentially get 4096 and with 1/4, 8192 and so on. This was the 2 lines of code mentioned, just turning the scale into a fraction. Now when we train on it, we can get it to realise the in between positional embedding and use the max tokens 2048 as a float scale possibly reaching a whole sentence per 1 positional embedding. Neat huh?

**Comment by Jeduh** [comment]
Do you get what i mean now? They've cracked it with a really simple solution that anyone could play around with, even me :)

**Comment by Jeduh** [comment]
Still cant get the model to train :/ 

I get this now
AttributeError: 'int' object has no attribute 'strip'
Which makes no sense because why is it trying to strip an integer haha.

I'm gonna move out of oogabooga now and give the og alpaca lora 4 bit, I'd love to keep in contact with you about my findings though.

**Comment by Jeduh** [comment]
I managed to get a train running with 4096 context on alpaca lora 4bit :)

**Comment by Jeduh** [comment]
i wrote the docker compose and edited the docker file for it if you want them to run your own

**Comment by Atinoda** [comment]
Congratulations - that's an awesome achievement, and right at the cutting edge of open-source LLM deployments! If you're happy to share the files, then please do - I'll test and try to integrate them as a variant here.

**Comment by Jeduh** [comment]
give me your contact

**Comment by Atinoda** [comment]
Would you be happy to post the edited files here? Or fork the repo then link / PR your changes in a new branch? If we develop in a public forum then it adds visibility for other people, and opens the door for other collaborators. How do you think that your results compare to Mosaic's [model](https://www.mosaicml.com/blog/mpt-7b)?

**Comment by Jeduh** [comment]
I know, already created a repo and all, just wanted to have any form of pm. Ill add you to the repo tomorrow. Well MPT 7b Isn't as good as llama right off the bat and the long contexts, to which kaiokendev released [this](https://huggingface.co/kaiokendev/superhot-30b-8k-no-rlhf-test) 30b 8k tokens and that performs great much better than MPT imo, even their 30B. The one thing I'll be excited for though is MPT 30B Storywriter.

**Comment by Atinoda** [comment]
Stretched contexts through modified positional encoding is included in the `ExLlama` loader via the `max_seq_len` `compress_pos_emb` options. Check it out! I am going to close this issue as completed, because the motivation of the 4-bit training feature request was to replicate this functionality.
